INSERT INTO "ROL" (ID_ROL, ROL) VALUES ('1', 'admin');

INSERT INTO "ROL" (ID_ROL, ROL) VALUES ('2', 'prof');

INSERT INTO "ROL" (ID_ROL, ROL) VALUES ('3', 'cli');

INSERT INTO "USUARIO" (ID_USUARIO, USUARIO, CONTRASENIA, ROL_ID_ROL) VALUES ('1', 'admin', 'admin', '1');

INSERT INTO "USUARIO" (ID_USUARIO, USUARIO, CONTRASENIA, ROL_ID_ROL) VALUES ('2', 'prof', 'prof', '2');

INSERT INTO "USUARIO" (ID_USUARIO, USUARIO, CONTRASENIA, ROL_ID_ROL) VALUES ('3', 'cli', 'cli', '3');

CREATE SEQUENCE idProfesional INCREMENT BY 1 START WITH 1;

